site_name: Proficient Programming with C#
site_description: C# Course — Beginner to Advanced
site_author: Sir Aousaja

theme:
  name: material

nav:
  - Home: index.md

  - Sessions:
      - Session 01 — C# Fundamentals: sessions/session-01.md
      - Session 02 — Variables & Data Types: sessions/session-02.md
      - Session 03 — Conditions: sessions/session-03.md
      - Session 04 - Loops & Iteration: sessions/session-04.md

  - Exercises:
      - Session 01 Exercises: exercises/session-01.md
      - Session 04 Exercises: exercises/session-04.md

  - Assignments:
      - Session 01 Assignment: assignments/session-01.md