// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
  
//   tutorialSidebar: [
//     // 'intro',
//     // 'hello',
//     // {
//     //   type: 'category',
//     //   label: 'Getting Started',
//     //   items: ['../src/pages/my-first-page'],
//     // },
//     {
//       type: 'link',
//       label: 'Sessions',
//       href: '/session-01',   // the route of your page
//     },
//   ],
   
// };

// const sidebars = {
//   // Main sidebar
//   tutorialSidebar: [
//     {
//       type: "doc",
//       id: "home",          // or "home" depending on your file name
//       label: "Home",
//     },
//     {
//       type: "category",
//       label: "Sessions",
//       collapsed: false,     // keep open by default
//       items: [
//         "sessions/session-01",
//         "sessions/session-02",
//         "sessions/session-03",
//         "sessions/session-04",
//         "sessions/session-05",
//         "sessions/session-06",
//         // "sessions/session-07",
//       ],
//     },
//     {
//       type: "category",
//       label: "Exercises",
//       collapsed: true,
//       items: [
//         "exercises/session-01",
//         "exercises/session-04",
//         // Add more exercises later
//       ],
//     },
//   ],
// };

// // sidebarItems.js  (or put this inside your Sidebar component)



// export default sidebars;
